In [1]:
import pandas as pd

In [9]:
education_df = pd.read_excel('../Data/Education.xlsx', header=3)

In [10]:
education_df.head()

,FIPS Code,State,Area name,2003 Urban Influence Code,2013 Urban Influence Code,2013 Rural-urban Continuum Code,2023 Rural-urban Continuum Code,"Less than a high school diploma, 1970","High school diploma only, 1970","Some college (1-3 years), 1970",...,"Percent of adults completing some college or associate's degree, 2008-12","Percent of adults with a bachelor's degree or higher, 2008-12","Less than a high school diploma, 2018-22","High school diploma only, 2018-22","Some college or associate's degree, 2018-22","Bachelor's degree or higher, 2018-22","Percent of adults with less than a high school diploma, 2018-22","Percent of adults with a high school diploma only, 2018-22","Percent of adults completing some college or associate's degree, 2018-22","Percent of adults with a bachelor's degree or higher, 2018-22"
0,0,US,United States,NaN,NaN,NaN,NaN,52373312.0,34158051.0,11650730.0,...,28.993579,28.484955,24599698.0,59741825.0,64508122.0,77751347.0,10.855953,26.364326,28.467714,34.312006
1,1000,AL,Alabama,NaN,NaN,NaN,NaN,1062306.0,468269.0,136287.0,...,29.022866,22.264896,421180.0,1041725.0,1032770.0,932845.0,12.284601,30.384102,30.122910,27.208387
2,1001,AL,Autauga County,2.0,2.0,2.0,2.0,6611.0,3757.0,933.0,...,29.618142,21.707831,3857.0,12517.0,11935.0,11879.0,9.597392,31.146113,29.697920,29.558575
3,1003,AL,Baldwin County,5.0,2.0,3.0,3.0,18726.0,8426.0,2334.0,...,31.819503,27.741591,14031.0,46391.0,52215.0,54385.0,8.400690,27.775383,31.262349,32.561579
4,1005,AL,Barbour County,6.0,6.0,6.0,6.0,8120.0,2242.0,581.0,...,25.771784,14.524286,4155.0,6507.0,4913.0,2100.0,23.507779,36.814710,27.796322,11.881188

In [11]:
education_df.columns

Index(['FIPS Code', 'State', 'Area name', '2003 Urban Influence Code',
       '2013 Urban Influence Code', '2013 Rural-urban Continuum Code',
       '2023 Rural-urban Continuum Code',
       'Less than a high school diploma, 1970',
       'High school diploma only, 1970', 'Some college (1-3 years), 1970',
       'Four years of college or higher, 1970',
       'Percent of adults with less than a high school diploma, 1970',
       'Percent of adults with a high school diploma only, 1970',
       'Percent of adults completing some college (1-3 years), 1970',
       'Percent of adults completing four years of college or higher, 1970',
       'Less than a high school diploma, 1980',
       'High school diploma only, 1980', 'Some college (1-3 years), 1980',
       'Four years of college or higher, 1980',
       'Percent of adults with less than a high school diploma, 1980',
       'Percent of adults with a high school diploma only, 1980',
       'Percent of adults completing some college (1-3 years), 1980',
       'Percent of adults completing four years of college or higher, 1980',
       'Less than a high school diploma, 1990',
       'High school diploma only, 1990',
       'Some college or associate's degree, 1990',
       'Bachelor's degree or higher, 1990',
       'Percent of adults with less than a high school diploma, 1990',
       'Percent of adults with a high school diploma only, 1990',
       'Percent of adults completing some college or associate's degree, 1990',
       'Percent of adults with a bachelor's degree or higher, 1990',
       'Less than a high school diploma, 2000',
       'High school diploma only, 2000',
       'Some college or associate's degree, 2000',
       'Bachelor's degree or higher, 2000',
       'Percent of adults with less than a high school diploma, 2000',
       'Percent of adults with a high school diploma only, 2000',
       'Percent of adults completing some college or associate's degree, 2000',
       'Percent of adults with a bachelor's degree or higher, 2000',
       'Less than a high school diploma, 2008-12',
       'High school diploma only, 2008-12',
       'Some college or associate's degree, 2008-12',
       'Bachelor's degree or higher, 2008-12',
       'Percent of adults with less than a high school diploma, 2008-12',
       'Percent of adults with a high school diploma only, 2008-12',
       'Percent of adults completing some college or associate's degree, 2008-12',
       'Percent of adults with a bachelor's degree or higher, 2008-12',
       'Less than a high school diploma, 2018-22',
       'High school diploma only, 2018-22',
       'Some college or associate's degree, 2018-22',
       'Bachelor's degree or higher, 2018-22',
       'Percent of adults with less than a high school diploma, 2018-22',
       'Percent of adults with a high school diploma only, 2018-22',
       'Percent of adults completing some college or associate's degree, 2018-22',
       'Percent of adults with a bachelor's degree or higher, 2018-22'],
      dtype='object')

In [ ]:
[i if 'education_df.columns' in  for i in education_df.columns]

In [14]:
l = []
for i in education_df.columns:
    if 'Percent of adults with a high school' in i:
        l.append(i)
l

['Percent of adults with a high school diploma only, 1970',
 'Percent of adults with a high school diploma only, 1980',
 'Percent of adults with a high school diploma only, 1990',
 'Percent of adults with a high school diploma only, 2000',
 'Percent of adults with a high school diploma only, 2008-12',
 'Percent of adults with a high school diploma only, 2018-22']

In [15]:
final_df = education_df[['FIPS Code', 'Percent of adults with a high school diploma only, 2000', 'Percent of adults with a high school diploma only, 2008-12', 'Percent of adults with a high school diploma only, 2018-22']]

In [17]:
final_df.columns = ['fips_code', 'pct_no_hs_degree_2000', 'pct_no_hs_degree_08_12', 'pct_no_hs_degree_18_22']

In [18]:
final_df.head()

,fips_code,pct_no_hs_degree_2000,pct_no_hs_degree_08_12,pct_no_hs_degree_18_22
0,0,28.6,28.241155,26.364326
1,1000,30.4,31.309957,30.384102
2,1001,33.8,33.786706,31.146113
3,1003,29.6,28.816463,27.775383
4,1005,32.4,33.294700,36.814710

In [19]:
countydf = pd.read_csv('../Cleaned Data/cleaned_us_counties.csv',)

In [20]:
fips_codes_is_present = final_df[final_df['fips_code'].isin(countydf['fips_code'])]

In [21]:
fips_codes_is_present.shape

(3213, 4)

In [23]:
fips_codes_is_present.head()

,fips_code,pct_no_hs_degree_2000,pct_no_hs_degree_08_12,pct_no_hs_degree_18_22
2,1001,33.8,33.786706,31.146113
3,1003,29.6,28.816463,27.775383
4,1005,32.4,33.294700,36.814710
5,1007,35.7,41.609744,40.879121
6,1009,36.0,36.157404,35.313717

In [25]:
fips_codes_is_present.to_csv('../Cleaned Data/cleaned_education.csv', index=False)